@startuml "school management erm diagram"

abstract class Person {
   -id: number
   -identification_number: string
   -first_name: string
   -last_name: string
   -date_of_birth: date
   -sex: string
   -email: string
   -phone_number: string
   -address: string
}


class Teacher {
   -subjects: list<Subject>
}

class Student {
   -gradeLevel: number
   -enrolled_classes: list<Course>
   -grades: list<Grade>
   +assignGrade(teacher: Teacher, subject: Subject, grade: Grade): void
}

class Subject {
   -name: string
   -description: string
   +getTeachers(): list<Teacher>
   +getStudents(): list<Student>
}

class Enrollment {
   -subject: Subject
   -grade: string
   -remarks: string
}

Person <|-- Teacher
Person <|-- Student

Student --|> Enrollment : 0..*
Enrollment --|> Subject : 0..1
Teacher --|> Subject : 0..*

@enduml